package com.vmpkp.HRManagementSystem.Services;

import com.vmpkp.HRManagementSystem.DTO.PaySlipDto;
import jakarta.mail.MessagingException;
import jakarta.mail.internet.MimeMessage;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.core.io.ByteArrayResource;
import org.springframework.mail.MailException;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.mail.javamail.MimeMessageHelper;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
public class SendEmailService {

    @Autowired
    private JavaMailSender emailSender;

    @Autowired
    private GeneratePdfService generatePdfService;

    public void generateAndSendPayslipEmails(List<PaySlipDto> paySlipDtoList) {
        for (PaySlipDto paySlipDto : paySlipDtoList) {
            try {
                byte[] payslipPdf = generatePdfService.generatePdf(paySlipDto);
                String recipientEmail = paySlipDto.getEmail();
                sendEmailWithAttachment(recipientEmail, payslipPdf);
            } catch (Exception e) {
                // Handle any exceptions
                e.printStackTrace();
            }
        }
    }



    private void sendEmailWithAttachment(String recipientEmail, byte[] attachment) {
        try {

            MimeMessage message = emailSender.createMimeMessage();
            MimeMessageHelper helper = new MimeMessageHelper(message, true);
            helper.setTo(recipientEmail);
            helper.setSubject("Payslip");
            helper.setText("This is an autogenerated email. Please do not reply to it.\n" +
                    "Below is the payslip attached to this email.");

            // Attach PDF
            helper.addAttachment("payslip.pdf", new ByteArrayResource(attachment));

            // Send email
            emailSender.send(message);
            System.out.println("Email sent successfully to: " + recipientEmail);
        } catch (MessagingException | MailException e) {
            // Handle exceptions
            e.printStackTrace();
        }
    }


}
